### ISSUE TITLE
Bad Redirect(s).

### ISSUE THREAD

**Issue by Penguin-Guru** [vircadia/vircadia-dev-docs#4]
[This link](https://docs.vircadia.dev/developer/interface/command-line-parameters.html) sends me to a broken link page. That page does link to the correct page (which raises the question of why it stands in between at all), but what's weird is that it thinks I want to go to the "user documentation". Both the original link and the (I believe correct) link it suggests are in the developer documentation.

Also strange that the command line arguments to run the client are considered developer material.

**Comment by digisomni** [comment]
I believe this specific issue should be fixed now that the links have all been redone.

With regards to command line parameters, ideally those should only have to be used by a technical user or under an otherwise atypical circumstance.

**Comment by Penguin-Guru** [comment]
Not all technical users are developers, but it's up to you.
